server:
  port: 9000
  netty:
    port: 9001
spring:
  profiles:
    active: pro
  servlet:
    multipart:
      max-file-size: 100MB
  application:
    name: chat
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
chat:
  upload:
    file-path: ${user.dir}/upload/
